spring:
  datasource:
    platform: postgresql
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/products
    username: postgres
    password: 123456
    initialization-mode: never
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: none
    show-sql: false